apiVersion: v1
kind: Service
metadata:
  name: urbansole-srv
spec:
  type: NodePort
  selector:
    app: urbansole
  ports: 
    - name: urbansole
      protocol: TCP
      port: 4545
      targetPort: 4545